apiVersion: v1
kind: Pod
metadata:
  name: master-pod
  labels:
    app: master-app
spec:
  restartPolicy: Never
  containers:
    - name: master-container
      image: cutlery47/master-image:latest
      ports:
        - name: master-port
          containerPort: ${MASTER_PORT}
      volumeMounts:
        - name: ${VOLUME_NAME}
          mountPath: ${MAPPED_FILE_DIRECTORY}
      envFrom:
        - configMapRef:
            name: ${CONFIG_MAP_NAME}
  volumes:
    - name: ${VOLUME_NAME}
      hostPath:
        path: ${MINIKUBE_FILE_DIRECTORY}
        type: Directory
---
apiVersion: v1
kind: Service
metadata:
  name: ${MASTER_HOST}
spec:
  type: NodePort
  selector: 
    app: master-app
  ports:
    - protocol: TCP
      port: ${MASTER_PORT}
      targetPort: master-port
      nodePort: 30001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deployment
spec:
  replicas: ${WORKERS}
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - name: worker-container
        image: cutlery47/worker-image:latest
        env:
          - name: MASTER_HOST
            valueFrom:
              configMapKeyRef:
                name: env-map
                key: MASTER_HOST
          - name: MASTER_PORT
            valueFrom:
              configMapKeyRef:
                name: env-map
                key: MASTER_PORT
          - name: SETUP_DURATION
            valueFrom:
              configMapKeyRef:
                name: env-map
                key: SETUP_DURATION
          - name: COLLECT_INTERVAL
            valueFrom:
              configMapKeyRef:
                name: env-map
                key: COLLECT_INTERVAL
          - name: WORKER_TIMEOUT
            valueFrom:
              configMapKeyRef:
                name: env-map
                key: WORKER_TIMEOUT
