apiVersion: v1
kind: Pod
metadata:
  name: master-pod
  labels:
    app: master-app
spec:
  restartPolicy: Never
  containers:
    - name: master-container
      image: cutlery47/master-image:latest
      ports:
        - containerPort: 8080
          name: master-port
---
apiVersion: v1
kind: Service
metadata:
  name: master-service
spec:
  type: NodePort
  selector: 
    app: master-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: master-port
      nodePort: 30001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - name: worker-container
        image: cutlery47/worker-image:latest


