apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deployment
spec:
  replicas: 5
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - name: worker-container
        image: cutlery47/worker-image:latest
        imagePullPolicy: IfNotPresent
---
apiVersion: v1
kind: Pod
metadata:
  name: master-pod
  labels:
    app: master-app
spec:
  containers:
    - name: master-container
      image: cutlery47/master-image:latest
      imagePullPolicy: IfNotPresent
---
apiVersion: v1
kind: Service
metadata:
  name: master-service
spec:
  selector: 
    app: master-app
  ports:
    - protocol: TCP
    port: 8080
    targetPort: 8080

